galaxy_info:
  author: Fabin Wilfred
  description: "Nginx installation and minimal site provisioning"
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - linux
    - hardening
    - devops

dependencies: []
