galaxy_info:
  author: Fabin Wilfred
  description: "Chrony-based NTP time synchronization"
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - linux
    - hardening
    - devops

dependencies: []
