---
# defaults file for roles/firewall

firewall_enabled: true

firewall_default_incoming_policy: deny
firewall_default_outgoing_policy: allow

firewall_ssh_port: "{{ ssh_port | default(22) }}"
firewall_http_enabled: true
firewall_http_port: 80
